In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import os

In [3]:
os.getcwd()


'E:\\Rudhra\\Study for reputation\\Kaggle projects\\Titanic Machine Learning from Disaster'

In [4]:
os.listdir()

['.ipynb_checkpoints',
 'titanic',
 'titanic.zip',
 'Titanic_Test data preparation.ipynb',
 'Titanic_Training data preparation.ipynb']

In [5]:
os.chdir("E:\\Rudhra\\Study for reputation\\Kaggle projects\\Titanic Machine Learning from Disaster\\titanic")

In [6]:
os.listdir()

['gender_submission.csv', 'test.csv', 'Titanic_train_Cleaned.csv', 'train.csv']

In [7]:
Titanic_test = pd.read_csv("test.csv")

In [8]:
Titanic_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [9]:
Titanic_test.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
Titanic_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [12]:
Titanic_test.Age.describe()

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [13]:
Titanic_test.Age.fillna(29.699118, inplace=True)

In [14]:
Titanic_test.Age.describe()

count    418.000000
mean      30.154603
std       12.636666
min        0.170000
25%       23.000000
50%       29.699118
75%       35.750000
max       76.000000
Name: Age, dtype: float64

In [15]:
Titanic_test.Ticket

0                  330911
1                  363272
2                  240276
3                  315154
4                 3101298
5                    7538
6                  330972
7                  248738
8                    2657
9               A/4 48871
10                 349220
11                    694
12                  21228
13                  24065
14            W.E.P. 5734
15          SC/PARIS 2167
16                 233734
17                   2692
18       STON/O2. 3101270
19                   2696
20               PC 17603
21                C 17368
22               PC 17598
23               PC 17597
24               PC 17608
25              A/5. 3337
26                 113509
27                   2698
28                 113054
29                   2662
              ...        
388                364858
389                349909
390                 12749
391              PC 17592
392             C.A. 2673
393            C.A. 30769
394                315153
395         

In [16]:
a = []
for i in Titanic_test.Ticket:
    a.append(len(i.split(" ")))
a = pd.Series(a)
a.unique()

array([1, 2, 3], dtype=int64)

In [17]:
def TicSlno (x):
    if len(x.split(" ")) == 1:
        return(x.split(" ")[0])
    elif len(x.split(" ")) == 2:
        return(x.split(" ")[1])
    elif len(x.split(" ")) == 3:
        return (x.split(" ")[2])
    
    
    

In [21]:
Titanic_test[Titanic_test["Ticket"]=='LINE']

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [22]:
Ticket = Titanic_test['Ticket'].map(TicSlno)

In [23]:
Titanic_test['Ticket'] = pd.to_numeric(Ticket)

In [24]:
Titanic_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [25]:
Titanic_test.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket           int64
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [26]:
Titanic_test.Fare.describe()

count    417.000000
mean      35.627188
std       55.907576
min        0.000000
25%        7.895800
50%       14.454200
75%       31.500000
max      512.329200
Name: Fare, dtype: float64

In [28]:
Titanic_test[Titanic_test["Fare"] == 0]

PassengerId  Pclass                                   Name   Sex  \
266         1158       1  Chisholm, Mr. Roderick Robert Crispin  male   
372         1264       1                Ismay, Mr. Joseph Bruce  male   

           Age  SibSp  Parch  Ticket  Fare        Cabin Embarked  
266  29.699118      0      0  112051   0.0          NaN        S  
372  49.000000      0      0  112058   0.0  B52 B54 B56        S

In [29]:
Titanic_test[Titanic_test["Fare"].isnull()]

PassengerId  Pclass                Name   Sex   Age  SibSp  Parch  \
152         1044       3  Storey, Mr. Thomas  male  60.5      0      0   

     Ticket  Fare Cabin Embarked  
152    3701   NaN   NaN        S

In [30]:
Titanic_test.Cabin.isnull().sum()


327

In [32]:
Titanic_test.Cabin.unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object)

In [33]:
def Cabclass(x):
    if x[0] == 'A':
        return('A')
    elif x[0] == 'B':
        return('B')
    elif x[0] == 'C':
        return('C')
    elif x[0] == 'D':
        return('D')
    elif x[0] == 'E':
        return('E')
    elif x[0] == 'F':
        return('F')
    elif x[0] == 'G':
        return('G')
    elif x[0] == 'T':
        return('T')
    else :
        return(np.nan)

In [34]:
Titanic_test['Cabin'].fillna("NaN", inplace=True)

In [35]:
Titanic_test['Cabin']= Titanic_test['Cabin'].map(Cabclass)

In [37]:
Titanic_test.Cabin.unique()

array([nan, 'B', 'E', 'A', 'C', 'D', 'F', 'G'], dtype=object)

In [38]:
Titanic_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [39]:
Titanic_test = Titanic_test.drop('Name', axis=1)

In [40]:
Titanic_test =pd.get_dummies(Titanic_test)

In [41]:
Titanic_test.head()

PassengerId  Pclass   Age  SibSp  Parch   Ticket     Fare  Sex_female  \
0          892       3  34.5      0      0   330911   7.8292           0   
1          893       3  47.0      1      0   363272   7.0000           1   
2          894       2  62.0      0      0   240276   9.6875           0   
3          895       3  27.0      0      0   315154   8.6625           0   
4          896       3  22.0      1      1  3101298  12.2875           1   

   Sex_male  Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  Cabin_G  \
0         1        0        0        0        0        0        0        0   
1         0        0        0        0        0        0        0        0   
2         1        0        0        0        0        0        0        0   
3         1        0        0        0        0        0        0        0   
4         0        0        0        0        0        0        0        0   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           1           0  
1           0           0           1  
2           0           1           0  
3           0           0           1  
4           0           0           1

In [42]:
Titanic_test.dtypes

PassengerId      int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Ticket           int64
Fare           float64
Sex_female       uint8
Sex_male         uint8
Cabin_A          uint8
Cabin_B          uint8
Cabin_C          uint8
Cabin_D          uint8
Cabin_E          uint8
Cabin_F          uint8
Cabin_G          uint8
Embarked_C       uint8
Embarked_Q       uint8
Embarked_S       uint8
dtype: object

In [43]:
os.getcwd()

'E:\\Rudhra\\Study for reputation\\Kaggle projects\\Titanic Machine Learning from Disaster\\titanic'

In [44]:
Titanic_test.to_csv('Titanic_test_Cleaned.csv', index=False)